#!/usr/bin/env bash

set -e
set -u

talend_license_policy_script_path=$(readlink -e "${BASH_SOURCE[0]}")
talend_license_policy_script_dir="${talend_license_policy_script_path%/*}"

#source
source "${talend_license_policy_script_dir}/policy.sh"

declare license_policy
policy_public_read license.talend.com license_policy
echo "${license_policy}" > license.talend.com.policy
aws s3api put-bucket-policy --bucket license.talend.com --policy "file://${talend_license_policy_script_dir}/license.talend.com.policy"

