#!/usr/bin/env bash

set -e
set -u
set -o pipefail

script_path=$(readlink -e "${BASH_SOURCE[0]}")
script_dir="${script_path%/*}"

# shellcheck source=../../util/util.sh
source ${script_dir}/../../util/util.sh
# shellcheck source=../s3fs-util.sh
source ${script_dir}/../s3fs-util.sh


if [ is_s3fs_installed ]; then
    echo "s3fs installed"
else
    echo "s3fs not installed"
fi
